{{- if and (.Values.daemonset.enabled) (.Values.deployment.enabled) }}
{{- fail "Cannot enable a daemonset and deployment using HelmHarbor" }}
{{- end }}

{{- if .Values.daemonset.enabled -}}
{{ $imageTag := .Values.imageTag }}
{{ $imageDigest := .Values.imageDigest }}
{{ $volumes := .Values.volumes }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "HelmHarbor.fullname" . }}
  labels:
    {{- include "HelmHarbor.labels" . | nindent 4 }}
    {{- include "HelmHarbor.customLabels" . | indent 4 }}
spec:
  {{- if .Values.rollingUpdate.enabled }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "HelmHarbor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "HelmHarbor.selectorLabels" . | nindent 8 }}
        takadom/ttechiq: {{ now | unixEpoch | quote }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        {{- range $name, $container := .Values.containers }}
        - name: {{ $name }}
          args:
            {{- toYaml $container.args | nindent 12 }}
          {{- if $container.image.tag }}
          image: "{{ $container.image.name }}:{{ $container.image.tag }}"
          {{- else if $container.image.digest }}
          image: "{{ $container.image.name }}@{{ $container.image.digest }}"
          {{- else if $imageTag }}
          image: "{{ $container.image.name }}:{{ $imageTag }}"
          {{- else }}
          image: "{{ $container.image.name }}@{{ $imageDigest }}"
          {{- end }}
          imagePullPolicy: {{ $container.image.pullPolicy }}
          ports:
            {{- range $container.ports }}
            - containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          {{- if $container.environmentValueFromResource }}
          envFrom:
            {{- range $key, $value := $container.environmentValueFromResource }}
            {{- if eq $value.resourceType "configMapRef" }}
            - configMapRef:
                name: {{ include "HelmHarbor.fullname" $ }}-{{ $value.resourceName }}
            {{- end }}
            {{- end }}
          {{- end }}
          env:
            {{- range $key, $value := $container.environmentValueFrom }}
            - name: {{ $key }}
              {{- if $value.fieldRef }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $value.fieldRef }}
              {{- end }}
              {{- if $value.resourceFieldRef }}
              valueFrom:
                resourceFieldRef:
                  resource: {{ $value.resourceFieldRef }}
                  {{- if $value.containerName }}
                  containerName: {{ $value.containerName }}
                  {{- end }}
                  {{- if $value.divisor }}
                  divisor: {{ $value.divisor }}
                  {{- end }}
              {{- end }}
            {{- end }}
            {{- range $key, $value := $container.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := $container.secretValueFrom }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
            {{- end }}

          livenessProbe:
            {{- toYaml $container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $container.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml $container.startupProbe | nindent 12 }}
          resources:
            {{- toYaml $container.resources | nindent 12 }}
          volumeMounts:
            {{- range $name, $dst := $container.volumes }}
            - mountPath: {{ $dst }}
              name: {{ $name }}
            {{- end }}
          {{- end }}
      volumes:
        {{- range $name, $path := $volumes }}
        - name: {{ $name }}
          hostPath:
            path: {{ $path }}
            type: Directory
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
