apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "HelmHarbor.fullname" . }}
  labels:
    {{- include "HelmHarbor.labels" . | nindent 4 }}
    {{- include "HelmHarbor.customLabels" . | indent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "HelmHarbor.selectorLabels" . | nindent 6 }}
