{{- if .Values.secret.enabled -}}
{{- range $i, $config := .Values.secret.configs }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "HelmHarbor.fullname" $ }}-{{ $config.name }}
  labels:
    {{- include "HelmHarbor.labels" $ | nindent 4 }}
    {{- include "HelmHarbor.customLabels" $ | indent 4 }}
data:
  {{- range $key, $val := $config.values }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end -}}
{{- end -}}
