{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmharbor.serviceAccountName" . }}
  labels:
    {{- include "helmharbor.labels" . | nindent 4 }}
    {{- include "helmharbor.customLabels" . | indent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
